### ISSUE TITLE
How garbage collecting works?

### ISSUE THREAD

**Issue by tailhook** [Storyyeller/easy_strings#1]
Hi,

The library is described as "Ergonomic, garbage collected strings for Rust.", but I don't see anything that documents garbage collector and also can't find any code that does garbage collecting. Is it in "to do" or am I missing something?

**Comment by Storyyeller** [comment]
The strings are reference counted. Since they can't hold references to anything else, there is no need for fancy tracing GC.

**Comment by tailhook** [comment]
Ah, sorry I've looked at [this](https://github.com/Storyyeller/easy_strings/blob/master/src/lib.rs#L34) and couldn't find where this hashmap is cleaned. Now I see that it's just for static strings so it's okay.

Thanks for quick answer!
